version: "3.9"

services:
  app:
    container_name: t3
    platform: "linux/amd64"
    image: jay75chauhan/t3_crud_docker:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres"
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
